name: cape-signature-gen
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - transformers
      - pandas
      - tqdm
      - jupyter
      - matplotlib
      - scikit-learn